CC = gcc
CXX = g++ 
OBJ = rungeKutta4th.o
LDLIBS = -DWIN32 -lglut32 -lglut32 -lopengl32 -lglu32 

#.cpp:
#	$(CC)  $@.cpp $(OBJ) $(LDLIBS) -o $@

p8-pendulum:	p8-pendulum.cpp rungeKutta4th.o

p8-pendulumThree:	p8-pendulumThree.cpp rungeKutta4th.o

