# For linux replace the next line with
# CC =  gcc
# and you may have to add -L/usr/X11R6/lib to LDLIBS

CC = gcc

LDLIBS = -DWIN32 -lglut32 -lopengl32 -lglu32 

p8-walkingDog:	p8-walkingDog.c dogParts.o
